name: Update metadata.json
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Get list of markdown files
      id: files
      run: |
        echo "files=$(find . -type f -name 'markdown.txt') >> $GITHUB_OUTPUT"

    - name: Generate metadata index
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const path = require('path');

          const files = "${{ steps.files.outputs.files }}".split("\n").map(f => f.trim()).filter(f => f !== "");

          const metadataIndex = {};

          for (const file of files) {
            const content = fs.readFileSync(file, 'utf8');
            const metadata = {};
            metadataText = content.split("### ENDMETADATA ###")[0];
            let pairs = metadataText.split(';').map(pair => pair.trim()).filter(pair => pair != "");
            pairs.forEach(pair => {
                let [key, value] = pair.split(':').map(part => part.trim());
                metadata[key] = value;
            });
            metadataIndex[file] = metadata;
          }
          core.warning(process.env.GITHUB_WORKSPACE)
          fs.readdir(process.env.GITHUB_WORKSPACE, (err, files) => {
            files.forEach(file => {
              core.warning(file);
            });
          });
          const indexFilePath = path.join(process.env.GITHUB_WORKSPACE, 'markdown', 'metadata.json');
          fs.writeFileSync(indexFilePath, JSON.stringify(metadataIndex, null, 2));
